### ISSUE TITLE
[Suggestion] Add comment to audio page about adjusting playback speed

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-manual#7]
I kept clicking and dragging the playback speed button but it didn't so anything. I had to search the Discord to find you had to scroll while hovering over it.

Clarifying this in the docs would be useful.

**Comment by jzohrab** [comment]
Thanks, will do!

**Comment by jzohrab** [comment]
Done, it will be live in a few minutes.  Updated to:

> You can do the usual things: start and pause the player (either with the buttons or the space bar), and fast-forward and rewind.  The "sticky player" toggle sticks the player to the bottom of the screen.
> 
> You can increase and decrease the playback speed by hovering over the playback speed control and scrolling up or down.  Clicking it resets the playback speed to 1.0, the regular speed.
